### ISSUE TITLE
Sprint 2 Semana 3 - 2. Crear una interfaz para que el administrador visualice productos

### ISSUE THREAD

**Issue by Carolinrg** [Javasteam/desarrolloweb#7]

**Comment by Carolinrg** [comment]
- [x] Es posible para el administrador visualizar los productos creados en el sistema

**Comment by georgeboy2212** [comment]
Se crea interfaz inicial para visualizar los productos leidos del archivo data.js.

**Comment by georgeboy2212** [comment]
Se crea interfaz inicial para visualizar los productos leidos del archivo data.js.
